name: Run AI Affiliate Agent

on:
  #schedule:
  #  - cron: "0 * * * *"  # Run hourly at the start of every hour
  workflow_dispatch:  # Allows manual execution from the Actions tab

permissions:
  contents: write  # Grants permission to push changes

jobs:
  run_script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify ACTION_PAT Secret
        env:
          ACTION_PAT: ${{ secrets.ACTION_PAT }}
        run: |
          if [ -z "${ACTION_PAT}" ]; then
            echo "ACTION_PAT is not set!"
            exit 1
          fi

      - name: Run AI Agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python src/main.py

      - name: Commit and push changes
        env:
          ACTION_PAT: ${{ secrets.ACTION_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/results.json
          git diff --cached --quiet || git commit -m "Update results"
          git push https://x-access-token:${{ secrets.ACTION_PAT }}@github.com/${{ github.repository }}.git main

      - name: Trigger GitHub Pages Rebuild (Optional)
        env:
          ACTION_PAT: ${{ secrets.ACTION_PAT }}
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.ACTION_PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/pages/builds
